### ISSUE TITLE
missing Linux version on conda-forge for v1.6

### ISSUE THREAD

**Issue by cokelaer** [conda-forge/pykwalify-feedstock#4]
@jakirkham 

Following a previous pull-request (https://github.com/conda-forge/pykwalify-feedstock/pull/3), pykwalify 1.6 was updated on conda-forge. 

However, I've noticed that only the win-32/win-64 and osx-64 are available: Linux is not

https://anaconda.org/conda-forge/pykwalify/files

Do you have any ideas why the Linux version is missing (v1.5 had the 3 flavours)

**Comment by jakirkham** [comment]
I think the bot stopped watching the repo, which stopped CircleCI from showing up. Fixed that with issue ( https://github.com/conda-forge/pykwalify-feedstock/issues/5 ). Now we just need to trigger a new build. So put dummy changes together in PR ( https://github.com/conda-forge/pykwalify-feedstock/pull/6 ). Looks like CircleCI is running there.

**Comment by jakirkham** [comment]
Linux builds are now uploaded. :) Thanks for the report.

**Comment by cokelaer** [comment]
brilliant thanks !
